config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

get '/pages/browse', to: 'pages#browse'

resources :users, only: [:new, :create] do
    put 'favorites', on: :member
    resources :favorites
end

# get '/favorites' => 'favorites#index'

resources :sessions, only: [:new, :create, :destroy]

resources :regions 

resources :genres

# resources :favorites, only: [:index, :destroy]
# get '/favorites' => 'favorites#index'

resources :songs do
    resources :favorites, shallow: true
end

get '/my_songs',  to: 'songs#my_songs', as: 'my_songs'

get '/login', to: 'sessions#new'

get '/logout', to: 'sessions#destroy'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :song
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :regions, through: :genre_regions
    has_many :songs, dependent: :destroy
end

app/models/genre_region.rb
class GenreRegion < ApplicationRecord
  belongs_to :genre
  belongs_to :region
end

app/models/region.rb
class Region < ApplicationRecord


    has_many :regions, through: :genre_regions
    has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  belongs_to :region
  belongs_to :genre
  has_many :favorites
  has_one_attached :album_cover
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true

    has_many :songs
    has_many :favorites
    has_many :favorite_songs, through: :favorites, source: :song
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private

    helper_method :current_user

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def authorize
        redirect_to login_path, alert: 'Log in to access songs, ¡por favor!' unless current_user
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :authorize, only: [:index, :destroy]
    def index
        @favorite_songs = current_user.favorite_songs
    end

    def destroy
        song = Song.find(params[:song_id])
        current_user.favorite_songs.delete(song)
        redirect_to user_favorites_path(current_user.id)
    end


end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def browse
        @region = Region.all
    end

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
    def index
        @regions = Region.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user= User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to pages_browse_path, notice: 'Logged in!'
        else
            flash.now.alert = 'Invalid login credentials - try again!'
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
    end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :set_song, only: [:show, :edit, :update, :destroy]
    before_action :authorize

    def index

        @songs = Song.all 
        @header = ''

        if params[:sort_by]
            p '#' * 100
            if params[:sort_by] == 'Artist'
                @songs = @songs.order('artist ASC')
            elsif params[:sort_by] == 'Title'
                @songs = @songs.order('title ASC')
            elsif params[:sort_by] == 'Album'
                @songs = @songs.order('album ASC')
            end
        end 

        if !params[:region_id].blank? && !params[:genre_id].blank?
            p '!' * 100
            @songs = @songs.where(region_id: params[:region_id], genre_id: params[:genre_id])
            @heading = ' ~ ' + Region.find(params[:region_id]).name + ' ~  &  ~ ' + Genre.find(params[:genre_id]).name + ' ~ ' 
            @list_countries = Region.find(params[:region_id]).countries 
        end 

        if !params[:region_id].blank? && params[:genre_id].blank?
            p '@' * 100
            @songs = @songs.where(region_id: params[:region_id])
            @heading = ' ~ ' + Region.find(params[:region_id]).name + ' ~ ' 
            @list_countries = Region.find(params[:region_id]).countries
        end

        if !params[:genre_id].blank? && params[:region_id].blank?
            p '$' * 100
            @songs = @songs.where(genre_id: params[:genre_id])
            @heading = ' ~ ' + Genre.find(params[:genre_id]).name + ' ~ '
        end

        if params[:genre_id].blank? && params[:region_id].blank?
            p '%' * 100
            @songs = @songs
        end

        if !params[:region_id].blank? && !params[:genre_id].blank? && !params[:sort_by].blank?
            p '*' * 100
            _attr = params[:sort_by].downcase
            @songs = @songs.where(region_id: params[:region_id], genre_id: params[:genre_id]).order("#{_attr} ASC")
        end

        if params[:sort_by].blank? && params[:genre_id].blank? && params[:region_id].blank?
            p '&' * 100
            @songs = @songs
        end
    end

    def new
        @song = Song.new
    end

    def create
        @song = Song.new(song_params)
        @song.user_id = current_user.id

        if params[:song][:album_cover]
            @song.album_cover.attach(params[:song][:album_cover])
        end

        if @song.save
            redirect_to songs_path, notice: 'You added a new song! ¡Gracias!'
        else 
            render new, notice: 'Uh oh, something went wrong! Try again!'
        end
    end

    def my_songs
        @songs = current_user.songs
    end 

    def edit
        puts @song
    end

    def update
        @song = Song.find(params[:id])
        if @song.update(song_params)
            redirect_to @song, notice: 'Song updated, ¡Felicidades!'
        else 
            render :edit
        end
    end

    def show
        @song = Song.find(params[:id])
    end

    def destroy
    end

    private
    def set_song
        @song = Song.find(params[:id])
    end

    def song_params
        params.require(:song).permit(:title, :artist, :album, :genre_id, :region_id, :album_cover, :sort_by)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          flash[:notice] = "You have successfully signed up!"
          redirect_to pages_browse_path
        else
          render :new
        end
    end

    def favorites
      song = Song.find(params[:song_id]) 
      current_user.favorite_songs << song
      redirect_to songs_path(region_id: params[:region_id], genre_id: params[:genre_id])
    end
    
    private
    
        def user_params
          params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/index.html.erb
<h1> FAVORITED SONGS </h1>

<% if @favorite_songs.empty? %>
    <p id="nofaves-container"> <span id="nofaves" class="ohno">No favorited songs! Go find some!</span> </p>
    <%= link_to 'Browse Songs',  pages_browse_path, class: 'browse' %>
<% else %>
    <ul>
    <% @favorite_songs.each do |fave| %>
        <li>
        <p class="title"> <%= fave.title %> </p>
        <p class="artist"> Artist: <%= fave.artist %> </p>
        <p class="album"> Album: <%= fave.album%> </p>
        <p class="genre"> Genre: <%= fave.genre.name%> </p>
        <p class="region"> Region: <%= fave.region.name%> </p>
        <% unless fave.album_cover.attachment.nil? %>
            <%= image_tag fave.album_cover.service_url %>
        <% else %>
            <%= image_tag 'album-cover.png' %>
        <% end %> 
        <p> <%= link_to "DELETE", user_favorite_path(id: current_user.id, song_id: fave.id), method: :delete, data: {confirm: 'Are you sure?'}%> <p>
        <% end %>
    </ul>
<% end %>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Latin Beat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=Courgette|Glegoo" rel="stylesheet">    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if current_user %>
        <div id="logo1"><%= link_to '~ THE LATIN BEAT ~', pages_browse_path%></div>
        &nbsp;BIENVENIDOS, <%= current_user.name %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to '♥' ,  user_favorites_path(current_user.id) %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'MY SONGS', my_songs_path %>
        &nbsp;&nbsp;|&nbsp;&nbsp;        
        <%= link_to 'LOG OUT', session_path('durkey'), method: :delete %>
        </div>
      <% else %>
        <div id="logo2"><%= link_to '~ THE LATIN BEAT ~', pages_browse_path%></div>
        <%= link_to 'LOG IN', login_path %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'SIGN UP', new_user_path %>
      <% end %>
    </nav>
    <div id="yellow"> </div>
    <%= yield %>
  </body>
</html>

app/views/pages/browse.html.erb
<h1> BROWSE SONGS BY </h1>
<h2> REGION  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  <span>&nbsp;~&nbsp; or &nbsp;~&nbsp;</span>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GENRE</h2>

<%= form_tag({controller: :songs, action: :index},  {method: :get}) do  %>
    <%= select_tag(:region_id, content_tag(:option, 'Select REGION', value: '', class: 'dropdown') + options_from_collection_for_select(Region.all, :id, :name, class: 'dropdown-content'))%>

    <%= select_tag(:genre_id, content_tag(:option, 'Select GENRE', value: '') + options_from_collection_for_select(Genre.all, :id, :name))%>
    <br>
    <div id="go"><%= submit_tag 'Go'  %></div>
<% end %>

app/views/pages/home.html.erb
<h1>BIENVENIDOS TO THE LATIN BEAT</h1> 
<h2> <span>Explore all the musicá the world has to offer!</span></h2>
<%= image_tag 'salsa-dancing.jpg', class: 'cover' %>

app/views/songs/_form.html.erb
<%= form_with(model: @song, local: true) do |form| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'type-input' %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, class: 'type-input' %>
  </div>

  <div class="field">
    <%= form.label :album %>
    <%= form.text_field :album, class: 'type-input' %>
  </div>

	<div class="field">
  <%= form.label :album_cover , class: "fileContainer"%>
  <%= form.file_field :album_cover, class: "fileContainer" %>
  </div>
<!-- THESE need to be drop down menus -->
    <div class="field">
    <%= form.label :region, class: 'label' %>
    <%= form.select(:region_id, content_tag(:option, 'Choose REGION', value: '') + options_from_collection_for_select(Region.all, :id, :name), class: 'some-class')%>
    </div>

    <div class="field">
    <%= form.label :genre, class: 'label' %>
    <%= form.select(:genre_id, content_tag(:option, 'Choose GENRE', value: '') + options_from_collection_for_select(Genre.all, :id, :name))%>
    </div>
  <div class="actions">
    <%= form.submit 'Update Song', :class => "create", :id => 'update'%>
  </div>
<% end %>

app/views/songs/edit.html.erb
<!-- edit song -->
<h1> EDIT YOUR SONG </h1>


<%= render 'form', song: @song %>

<%= link_to 'Show', @song, class: 'browse' %> |
<%= link_to 'Back', my_songs_path, class: 'browse'  %>

app/views/songs/index.html.erb
<h1> SONGS </h1>
<div class="heading">
    <p> 
        <% if @heading %>
            <h3>Viewing songs for:</h3>
            <%= @heading %> 
        <%end%>
    </p>
    <p> 
        <% if @list_countries %>
            <h3> Countries include: </h3>
            <%= ' ~ ' + @list_countries + ' ~ ' %> 
        <%end%>
    </p>
</div>
<%= form_tag('/songs', method: :get) do %>
<%= hidden_field_tag :genre_id, params[:genre_id]%>
<%= hidden_field_tag :region_id, params[:region_id]%>
<div class='sort_label'><%= label_tag 'Sort songs by:'%></div>
 <%= select_tag 'sort_by', options_for_select(['Title', 'Artist', 'Album']), prompt: 'Select one', onchange: 'this.form.submit();'%>
<% end %>
<ul>
    <% @songs.each do |s| %>
    <li>
        <div class="listing">
            <div class="info">
                <p class="title"> <%= s.title %> </p>
                <p class="artist"> Artist: <%= s.artist %> </p>
                <p class="album"> Album: <%= s.album%> </p>
                <p class="genre"> Genre: <%= s.genre.name%> </p>
                <p class="region"> Region: <%= s.region.name%> </p>
            </div>
            <div class="pic">
                <% unless s.album_cover.attachment.nil? %>
                    <%= image_tag s.album_cover.service_url %>
                <% else %>
                    <%= image_tag 'album-cover.png' %>
                <% end %>
            </div>
        </div>    
        <% if !current_user.favorite_songs.exists?(s.id)%>
            <p class="heart">¿Te gusta? <%= link_to '♥', favorites_user_path(current_user, song_id: s.id, region_id: params[:region_id], genre_id: params[:genre_id]), method: :put %></p>
        <% else%>
            <p class="faved"> ♥ </p>
        <% end %>
    </li>   
    <% end %>
</ul>
<div class="footer">
    <p> DON'T SEE A CERTAIN SONG?</p>
    <p> <span class="ohno">¡Ay, caramba!</span> </p>
    <%= link_to 'ADD A SONG +', new_song_path, class: 'browse' %>
</div>

app/views/songs/my_songs.html.erb
<h1> MY SONGS </h1> 
<ul>
    <% @songs.each do |s| %>
    <li>
        <p class="title"> <%= s.title %> </p>
        <p class="artist"> Artist: <%= s.artist %> </p>
        <p class="album"> Album: <%= s.album %> </p>
        <p class="genre"> Genre: <%= s.genre.name%> </p>
        <p class="region"> Region: <%= s.region.name%> </p>
        <% unless s.album_cover.attachment.nil? %>
            <%= image_tag s.album_cover.service_url %>
        <% else %>
            <%= image_tag 'album-cover.png' %>
        <% end %>    
        <p> <%= link_to 'Edit this song', edit_song_path(s) %></p>
    </li>   
    <% end %>
</ul>

app/views/songs/new.html.erb
<%= form_with(model: @song, local: false) do |form| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'type-input' %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, class: 'type-input' %>
  </div>

  <div class="field">
    <%= form.label :album %>
    <%= form.text_field :album, class: 'type-input' %>
  </div>

  <div class="field">
  <%= form.label :album_cover %>
  <%= form.file_field :album_cover, class: "fileContainer" %>
  </div>
<!-- THESE need to be drop down menus -->
    <div class="field">
    <%= form.label :region, class: 'label' %>
    <%= form.select(:region_id, content_tag(:option, 'Choose REGION', value: '') + options_from_collection_for_select(Region.all, :id, :name))%>
    </div>

    <div class="field">
    <%= form.label :genre, class: 'label' %>
    <%= form.select(:genre_id, content_tag(:option, 'Choose GENRE', value: '') + options_from_collection_for_select(Genre.all, :id, :name))%>
    </div>
  <div class="actions">
    <%= form.submit 'Add Song', :class => "create", :id => 'update'%>
  </div>
<% end %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @song.genre.name %>
</p>

<p>
  <strong>Region:</strong>
  <%= @song.region.name %>
</p>

<p>
  <% unless @song.album_cover.attachment.nil? %>
      <%= image_tag @song.album_cover.service_url %>
  <% else %>
      <%= image_tag 'album-cover.png' %>
  <% end %> 
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', my_songs_path %>

app/views/users/new.html.erb
<h1>SIGN UP</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'type-input'%>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'type-input'%>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'type-input' %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'type-input' %>
  </div>
  <div class='actions'><%= f.submit 'SIGN UP', :class => "create" %></div>
<% end %>